steps:
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ 'cp', 'gs://engauge-room-api/secret/gcloud.json', 'file:////workspace/api-room/secrets/gcloud.json' ]
  - name: bash
    args: [ 'ls' ]
  - name: 'gcr.io/cloud-builders/docker'
    dir: '/workspace/api-room'
    args: [ 'build', '-t', 'gcr.io/emerald-rhythm-303318/api-room', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    dir: '/workspace/api-room'
    args: [ 'push', 'gcr.io/emerald-rhythm-303318/api-room' ]
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'engauge-api-room', '--image', 'gcr.io/emerald-rhythm-303318/api-room', '--region', 'us-east4', '--platform', 'managed']
images: [ 'gcr.io/emerald-rhythm-303318/api-room' ]