steps:
  - name: node
    entrypoint: npm
    dir: '/workspace/.git/ui-main'
    args: ['install']
  - name: node
    dir: '/workspace/.git/ui-main'
    entrypoint: npm
    args: ['run', 'build']

artifacts:
  objects:
    location: 'gs://engauge-ui-main/'
    paths: ['ui-main/build']