steps:
  - name: node
    entrypoint: npm
    dir: '/workspace/ui-main'
    args: ['install']
  - name: node
    entrypoint: npm
    dir: '/workspace/ui-main'
    args: ['run', 'build']
  - name: 'gcr.io/cloud-builders/gsutil'
    dir: 'workspace/ui-main'
    args: ['rsync', '-r', '/build', 'gs://engauge-ui-main']