steps:
  - name: node-install
    dir: '/ui-main'
    args: ['npm', install']
  - name: node-build
    entrypoint: npm
    dir: '/ui-main'
    args: ['npm', 'run', 'build']

artifacts:
  objects:
    location: 'gs://engauge-ui-main/'
    paths: ['ui-main/build']